# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-methylseq-1.5
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # nf-core dependencies
  - conda-forge::python=3.8.5
  - conda-forge::markdown=3.3.3
  - conda-forge::pymdown-extensions=8.1.1
  - conda-forge::pygments=2.7.4
  - conda-forge::pigz=2.5
  - bioconda::fastqc=0.11.9
  # Default Bismark pipeline
  - bioconda::trim-galore=0.6.6
  - bioconda::samtools=1.10
  - bioconda::bowtie2=2.4.2
  - bioconda::hisat2=2.2.1
  - bioconda::bismark=0.23.0
  - bioconda::qualimap=2.2.2d
  - bioconda::preseq=3.1.2
  - bioconda::multiqc=1.9
  # bwa-meth pipeline
  - bioconda::picard=2.22.2
  - bioconda::bwameth=0.2.2
  - bioconda::methyldackel=0.5.1
# added
  - bioconda::samblaster=0.1.24
  - bioconda::bedtools=2.29.1
  - bioconda::biscuit=0.3.16.20200420
  - bioconda::bcftools=1.10
  - conda-forge::parallel=20201122
  - gawk=5.1.0
